config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("oneragtime.users.urls", namespace="users")),
    path("bills/", include("oneragtime.bills.urls", namespace="bills")),
    path("cashcalls/", include("oneragtime.cashcalls.urls", namespace="cashcalls")),
    path("core/", include("oneragtime.core.urls", namespace="core")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

oneragtime/bills/urls.py
from django.urls import path

from oneragtime.bills.views import filter_bills
from oneragtime.bills.views import filtered_bills
from oneragtime.bills.views import generate_bills
from oneragtime.bills.views import get_bill
from oneragtime.bills.views import list_bills
from oneragtime.bills.views import validate_bill

app_name = "bills"
urlpatterns = [
    path("generate/", view=generate_bills, name="generate"),
    path("list/", view=list_bills, name="list"),
    path("filtered/", view=filtered_bills, name="filtered"),
    path("filter_by_investor/", view=filter_bills, name="filter_by_investor"),
    path("bill/<int:bill_pk>/", view=get_bill, name="bill"),
    path("validate/<int:bill_pk>/", view=validate_bill, name="validate"),
]

oneragtime/core/urls.py
from django.urls import path

from . import views

app_name = "core"
urlpatterns = [
    path("confirm_delete/", view=views.confirm_delete, name="confirm_delete"),
    path("delete_db/", view=views.delete_db, name="delete_db"),
    path("load_initial/", view=views.load_initial, name="load_initial"),
]

oneragtime/users/urls.py
from django.urls import path

from oneragtime.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

oneragtime/bills/models.py
from django.db import models

from oneragtime.investments.model_utils import InvestmentType
from oneragtime.investments.models import Investment
from oneragtime.investors.models import Investor

from .model_utils import BillStatus


# Create your models here.
class Bill(models.Model):
    investor_id = models.ForeignKey(Investor, on_delete=models.SET_NULL, null=True)
    investment_id = models.ForeignKey(Investment, on_delete=models.SET_NULL, null=True)
    fees_amount = models.FloatField()
    date_added = models.DateTimeField()
    fees_type = models.CharField(choices=InvestmentType.choices(), max_length=15)
    status = models.CharField(choices=BillStatus.choices(), max_length=15, default=BillStatus.CREATED.value)

oneragtime/cashcalls/models.py
from django.db import models

from oneragtime.bills.models import Bill
from oneragtime.bills.models import Investor

from .model_utils import InvoiceStatus


# Create your models here.
class CashCall(models.Model):
    total_amount = models.FloatField(default=0)
    IBAN = models.CharField(max_length=50, null=True)
    email_send = models.EmailField(null=True)
    invoice_status = models.CharField(
        choices=InvoiceStatus.choices(), max_length=15, default=InvoiceStatus.VALIDATED.value
    )
    bills = models.ManyToManyField(Bill, verbose_name="Bills")
    year = models.IntegerField()
    investor = models.ForeignKey(Investor, on_delete=models.SET_NULL, null=True)

    @classmethod
    def upsert_cashcall(cls, bill: Bill):
        year = bill.date_added.year
        investor = bill.investor_id
        cashcall, _ = cls.objects.get_or_create(
            year=year, investor=investor, invoice_status=InvoiceStatus.VALIDATED.value
        )
        cashcall.bills.add(bill)
        cashcall.total_amount = cashcall.compute_amount()
        cashcall.save()

    def compute_amount(self):
        total_amount = 0
        for bill in self.bills.all():
            total_amount += bill.fees_amount
        return total_amount

oneragtime/core/models.py
from django.db import models

# Create your models here.

oneragtime/investments/models.py
from django.db import models

from oneragtime.investors.models import Investor

from .model_utils import InvestmentType


# Create your models here.
class Investment(models.Model):
    investor_id = models.ForeignKey(Investor, on_delete=models.SET_NULL, null=True)
    startup_name = models.CharField(max_length=100)
    invested_ammount = models.IntegerField()
    percentage_fees = models.IntegerField()
    date_added = models.DateTimeField()
    fees_type = models.CharField(choices=InvestmentType.choices(), max_length=15)

oneragtime/investors/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.
class Investor(models.Model):
    name = models.CharField(max_length=100)
    adress = models.CharField(max_length=100)
    credit = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name

oneragtime/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for OneRagTime."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

oneragtime/bills/forms.py
from django import forms
from django.forms import fields

from oneragtime.investors.models import Investor

from .models import Bill


class BillForm(forms.Form):
    investor = forms.ModelChoiceField(
        queryset=Investor.objects.all(), widget=forms.Select(attrs={"onChange": "refresh()"}), label="Investor"
    )

    # class Meta:
    #     model = Bill
    #     fields = ["investor_id"]

    def clean(self):
        cleaned_data = super().clean()
        investor = Investor.objects.get(name=cleaned_data.get("investor"))
        bills = Bill.objects.filter(investor_id=investor)
        return cleaned_data, bills

oneragtime/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

oneragtime/bills/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string

from oneragtime.cashcalls.models import CashCall
from oneragtime.investors.models import Investor

from .forms import BillForm
from .model_utils import BillStatus
from .models import Bill
from .utils import generate_bills_upfront
from .utils import generate_bills_yearly


def list_bills(request):
    bills = Bill.objects.all()
    return render(request, "bills/list.html", {"bills": bills})


def generate_bills(request):
    upfront = generate_bills_upfront()
    yearly = generate_bills_yearly()
    modal_content = render_to_string("bills/modal_generate.html", {"upfront": upfront, "yearly": yearly}, request)
    return JsonResponse({"status": "ok", "modal": modal_content})


def filtered_bills(request):
    form = BillForm()
    return render(request, "bills/filtered.html", {"form": form})


def filter_bills(request):
    bills = Bill.objects.filter(investor_id=8)
    form = BillForm(data=request.POST)
    if form.is_valid():
        bills = form.cleaned_data[1]
        bills_html = render_to_string("bills/datatable.html", {"bills": bills}, request)
        return JsonResponse({"status": "ok", "bills_html": bills_html})
    return JsonResponse({"status": "nok", "bills_html": "NOT VALID"})


def get_bill(request, bill_pk):
    bill = Bill.objects.get(pk=bill_pk)
    bill_html = render_to_string("bills/modal_validate.html", {"bill": bill}, request)
    return JsonResponse({"status": "ok", "bill": bill_html})


def validate_bill(request, bill_pk):
    bill = Bill.objects.get(pk=bill_pk)
    bill.status = BillStatus.VALIDATED.value
    bill.save(update_fields=["status"])
    CashCall.upsert_cashcall(bill)
    bills = Bill.objects.filter(investor_id=bill.investor_id)
    bills_html = render_to_string("bills/datatable.html", {"bills": bills}, request)
    return JsonResponse({"status": "ok", "bills_html": bills_html})

oneragtime/cashcalls/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string

from .model_utils import InvoiceStatus
from .models import CashCall


# Create your views here.
def list_cashcalls(request):
    cashcalls = CashCall.objects.all()
    return render(request, "cashcalls/list_cashcalls.html", {"cashcalls": cashcalls})


def send_cashcall(request, pk_cashcall):
    cashcall = CashCall.objects.get(pk=pk_cashcall)
    cashcall.invoice_status = InvoiceStatus.SENT.value
    cashcall.save(update_fields=["invoice_status"])
    cashcall_html = render_to_string("cashcalls/cashcall_card.html", {"cashcall": cashcall}, request)
    cashcall_id = f"cashcall-{cashcall.id}"
    return JsonResponse({"status": "ok", "cashcall_html": cashcall_html, "cascall_id": cashcall_id})

oneragtime/core/views.py
from django.core.management import call_command
from django.http.response import JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string

from oneragtime.bills.models import Bill
from oneragtime.cashcalls.models import CashCall
from oneragtime.investments.models import Investment
from oneragtime.investors.models import Investor


def confirm_delete(request):
    bills = len(Bill.objects.all())
    cashcalls = len(CashCall.objects.all())
    invesments = len(Investment.objects.all())
    investors = len(Investor.objects.all())
    modal_confirm = render_to_string(
        "pages/modal_delete.html",
        {"bills": bills, "cashcalls": cashcalls, "invesments": invesments, "investors": investors},
        request,
    )
    return JsonResponse({"modal": modal_confirm})


def delete_db(request):
    call_command("flush", interactive=False)
    return JsonResponse({"status": "ok"})


def load_initial(request):
    call_command("loaddata", "investor")
    call_command("loaddata", "investments")
    return JsonResponse({"status": "ok"})

oneragtime/investments/views.py
from django.shortcuts import render

# Create your views here.

oneragtime/investors/views.py
from django.shortcuts import render

# Create your views here.

oneragtime/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

oneragtime/templates/bills/datatable.html
<table id="table_id" class="display">
    <thead>
        <tr>
            <th>Investor</th>
            <th>Investment</th>
            <th>Fees Amount</th>
            <th>Date Added</th>
            <th>Fees Type</th>
            <th>Validate</th>
        </tr>
    </thead>
    <tbody>
        {% for bill in bills %}
        <tr>
            <td>{{bill.investor_id.name}}</td>
            <td>{{bill.investment_id.startup_name}}</td>
            <td>{{bill.fees_amount}}</td>
            <td>{{bill.date_added}}</td>
            <td>{{bill.fees_type}}</td>
            <td>
            {% if bill.status == "created" %}
            <button class="btn btn-sm btn-info" id="{{bill.pk}}" onclick="getModal(this.id)"> Validate </button>
            {% elif bill.status == "validated" %}
            validated
            {% endif %}

            </td>
            
        </tr>
        {% endfor %}
    </tbody>
</table>

<script>
    function getModal(bill_id){
        let url = "{% url 'bills:bill' '0000' %}".replace("0000", bill_id)
        $.ajax({
            url: url,
            type: "GET",
            processData: false,
            contentType: false,
            success: function (data) {
               $("#modals").html(data.bill);
               $("#modals").modal("show");
               
            },

        });
    }
</script>

oneragtime/templates/bills/filtered.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Filter Bills{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col">
            <div id="loading" class="lds-dual-ring"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-10">
            <h1>Filter Bills</h1>
        </div>
    </div>
    <hr>
    <form>
        {{form|crispy}}
    </form>
    <hr>
    <div id="results"></div>

</div>
{% endblock content %}



{% block inline_javascript %}
{{ block.super }}
<script defer src="{% static 'js/datatables/jquery.dataTables.min.js' %}"></script>
<script>
    function refresh() {
        const formData = new FormData(document.querySelector('form'))
        const url = "{% url 'bills:filter_by_investor' %}"
        $.ajax({
            url: url,
            data: formData,
            headers: { 'X-CSRFToken': '{{ csrf_token }}' },
            type: "POST",
            processData: false,
            contentType: false,
            success:function(data) {
                $("#results").html(data.bills_html);
                $("#table_id").DataTable();
            },

        });
    }
</script>
{% endblock inline_javascript %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.css">
<link href="{% static 'css/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

oneragtime/templates/bills/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}List Bills{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col">
            <div id="loading" class="lds-dual-ring"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-10"><h1>List Bills</h1></div>
        <div class="col-2">
            <button id="generate-bills" class="btn btn-sm btn-success"> Generate bills</button>
        </div>
    </div>
    <hr>

    {% include "bills/datatable.html"%}

</div>
{% endblock content %}


{% block css %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.css">
<link href="{% static 'css/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block inline_javascript %}
{{ block.super }}
<script defer src="{% static 'js/datatables/jquery.dataTables.min.js' %}"></script>
<script>
    const generateUrl = "{% url 'bills:generate' %}"
</script>
<script defer src="{% static 'js/bills/bills.js' %}"></script>

{% endblock inline_javascript %}

oneragtime/templates/bills/modal_generate.html
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Succes generating bills</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Generated {{upfront}} upfront bills</p>
                <p>Generated {{yearly}} yearly bills</p>
            </div>
            <div class="modal-footer">
                <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>

oneragtime/templates/bills/modal_validate.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Bill</h5>
        </div>
        <div class="modal-body">
            <p><b>Investor:</b>  {{bill.investor_id.name}} </p>
            <p><b>Startup Name: </b>{{bill.investment_id.startup_name}}</p>
            <p><b>Fees: </b>{{bill.fees_amount}}</p>
            <p><b>Date: </b>{{bill.date_added}}</p>
            <p><b>Fees type: </b>{{bill.fees_type}}</p>
                
                
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" id="{{bill.pk}}" onclick="validateBill(this.id)">Validate</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
    </div>
</div>

<script>
    function validateBill(bill_id) {
        let url= "{% url 'bills:validate' '0000' %}".replace("0000", bill_id)
        $.ajax({
            url: url,
            type: "GET",
            processData: false,
            contentType: false,
            success: function (data) {
                $("#modals").modal("hide");
                $("#results").html(data.bills_html);
                $("#table_id").DataTable();
            },

        });
        }
</script>